import * as path from 'path';
import { readFileSafe, writeFileSafe, ensureDir, logger } from '../core/index.js';

export async function generateUnifiedDocs(outputDir: string): Promise<void> {
  logger.info('Generating unified documentation...');

  const contextDir = path.join(outputDir, 'context');
  const memoryDir = path.join(outputDir, 'memory');

  // Read available contexts
  const schemaContext = await readFileSafe(
    path.join(outputDir, 'database', 'schema-overview.md'),
  ).catch(() => '');
  const codebaseOverview = await readFileSafe(
    path.join(outputDir, 'codebase', 'codebase-overview.md'),
  ).catch(() => '');
  const architecture = await readFileSafe(
    path.join(outputDir, 'codebase', 'architecture.md'),
  ).catch(() => '');
  const businessLogic = await readFileSafe(
    path.join(outputDir, 'database', 'BUSINESS_LOGIC.md'),
  ).catch(() => '');
  const learnings = await readFileSafe(path.join(memoryDir, 'LEARN.md')).catch(() => '');

  // Generate AGENTS.md (Consolidated Context in QMD Format)
  const agentsContent = `
# Project Context

> Generated by DevMind for AI Agents (Claude, Cursor, Windsurf)

## Architecture
${architecture || '(No architecture context available)'}

## Database Schema
${schemaContext ? 'See schema-overview.md for details.' : '(No database context available)'}

## Business Logic
${businessLogic || '(No business logic detected)'}

## Codebase Overview
${codebaseOverview || '(No codebase overview available)'}

## Project Learnings
${learnings || '(No learnings recorded)'}

---

## Agent Capabilities

<tools>
  <tool name="devmind-scan">
    <description>Scan codebase structure and generate QMD summary.</description>
  </tool>
  <tool name="devmind-analyze">
    <description>Analyze code-to-database usage patterns.</description>
  </tool>
  <tool name="devmind-learn">
    <description>Save a new technical learning, pattern, or architectural decision to LEARN.md.</description>
    <arguments>
      <arg name="learning">The knowledge to save</arg>
      <arg name="category">Category (architecture, database, etc)</arg>
    </arguments>
  </tool>
  <tool name="devmind-context">
    <description>Get focused context for a specific directory or module.</description>
    <arguments>
      <arg name="focus">Path to focus on</arg>
    </arguments>
  </tool>
</tools>

## Instructions

### Cursor / Windsurf
- **Context:** Read this file and linked overviews.
- **Style:** Follow patterns in architecture.md.
- **Database:** Check schema-overview.md before writing SQL.

### Claude
- **Validation:** Run \`devmind validate\` before major changes.
- **Memory:** Check \`LEARN.md\` for past lessons.
`.trim();

  await writeFileSafe(path.join(outputDir, 'AGENTS.md'), agentsContent);

  // Generate unified index.json
  const index = {
    timestamp: new Date().toISOString(),
    version: '1.0.0',
    contexts: {
      agents: 'AGENTS.md',
      schema: 'database/schema-overview.md',
      codebase: 'codebase/codebase-overview.md',
      architecture: 'codebase/architecture.md',
      learnings: 'memory/LEARN.md',
    },
    metadata: {
      hasDatabase: !!schemaContext,
      hasCodebase: !!codebaseOverview,
    },
  };

  await writeFileSafe(path.join(outputDir, 'index.json'), JSON.stringify(index, null, 2));

  logger.success('Unified documentation generated:');
  logger.info(`   - ${path.join(outputDir, 'AGENTS.md')}`);

  // Generate devmind-tools.json (Tool Definitions for Agents)
  const tools = [
    {
      name: 'devmind_scan',
      description:
        'Scans the codebase to generate an up-to-date structural overview and architecture summary. Use this when you need to understand the project structure or find specific files.',
      parameters: {
        type: 'object',
        properties: {
          path: {
            type: 'string',
            description: 'The root path to scan (default: current directory)',
          },
        },
      },
    },
    {
      name: 'devmind_analyze',
      description:
        'Analyzes the codebase for database table usage. Returns a report mapping tables to files and identifying unused tables. Use this before modifying the database schema.',
      parameters: {
        type: 'object',
        properties: {
          path: {
            type: 'string',
            description: 'The root path to analyze (default: current directory)',
          },
        },
      },
    },
    {
      name: 'devmind_learn',
      description:
        "Saves a new technical learning, pattern, or architectural decision to the project's persistent memory (LEARN.md). Use this when you discover something important that future agents should know.",
      parameters: {
        type: 'object',
        properties: {
          learning: {
            type: 'string',
            description: 'The knowledge to save (concise, actionable)',
          },
          category: {
            type: 'string',
            description:
              'Category of learning (e.g., architecture, database, testing, performance)',
          },
        },
        required: ['learning'],
      },
    },
    {
      name: 'devmind_context',
      description:
        'Retrieves focused context for a specific directory or module. Use this to inspect file structure and exports without reading the entire codebase.',
      parameters: {
        type: 'object',
        properties: {
          focus: {
            type: 'string',
            description: "Path to focus on (e.g., 'src/database')",
          },
          query: {
            type: 'string',
            description: 'Keyword search query (optional)',
          },
        },
      },
    },
    {
      name: 'devmind_history',
      description:
        "Retrieves the project's evolution history (database changes, codebase growth). Use this to understand what has changed recently.",
      parameters: {
        type: 'object',
        properties: {
          type: {
            type: 'string',
            enum: ['unified', 'schema', 'codebase'],
            description: 'Type of history to view (default: unified)',
          },
        },
      },
    },
  ];

  await writeFileSafe(path.join(outputDir, 'devmind-tools.json'), JSON.stringify(tools, null, 2));
  logger.info(`   - ${path.join(outputDir, 'devmind-tools.json')}`);

  logger.info(`   - ${path.join(outputDir, 'index.json')}`);
}
